# Generated by Django 4.2.11 on 2024-06-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
    ]
