# Generated by Django 4.2.11 on 2024-06-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='tags',
            field=models.ManyToManyField(to='shop.producttag'),
        ),
    ]
