# Generated by Django 4.2.11 on 2024-06-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feature_pictures')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
            ],
        ),
    ]
