# Generated by Django 5.0.6 on 2024-06-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
