# Generated by Django 4.2.11 on 2024-06-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_delete_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='django_shop/profile_pictures'),
        ),
    ]
